<?php
$lang = array (
	'c_log_title'					=> 'Activity Log',
	'v_log_date_time'				=> 'Date / Time',
	'v_log_ip_addr'					=> 'IP Addr.',
	'v_log_user'					=> 'User',
	'v_log_action'					=> 'Action',
	'v_log_related_prj_pwd'			=> 'related [PRJ] / password',
	'v_log_related_pwd' 			=> 'Related Password',
	'v_log_additional_data'			=> 'Additional Data',
	'v_log_origin'					=> 'Origin',
	'v_log_no_entries'				=> 'There are no log entries with the current filter.',
	'v_log_filter'					=> 'Filter',
	'v_log_clear_filter' 			=> 'Clear Values and Hide Filter',

	'v_log_filter_date'				=> 'Date',
	'v_log_filter_date_always' 		=> 'Always',
	'v_log_filter_date_today' 		=> 'Today',
	'v_log_filter_date_yesterday' 	=> 'Yesterday',
	'v_log_filter_date_this_month' 	=> 'This month',
	'v_log_filter_date_prev_month' 	=> 'Previous month',
	'v_log_filter_date_this_year' 	=> 'This year',
	'v_log_filter_date_prev_year' 	=> 'Previous year',

	'v_log_origin_web'				=> 'Web',
	'v_log_origin_api'				=> 'API',

	'v_log_users_all'				=> 'All',
	'v_log_actions_all'				=> 'All',
	'v_log_origins_all'				=> 'All',

	// Actions
	'v_log_a_view_password' 		=> 'View password data',
	'v_log_a_view_project' 			=> 'View [PRJ]',
	'v_log_a_login_successful' 		=> 'Login successful',
	'v_log_a_login_failed' 			=> 'Login failed',
	'v_log_a_logout' 				=> 'Logout',
	'v_log_a_password_reset' 		=> 'Password reset (user)',
	'v_log_a_show_password' 		=> 'Show password',
	'v_log_a_view_project_log' 		=> 'View [PRJ] log',
	'v_log_a_view_log' 				=> 'View log',
	'v_log_a_view_passwords_list' 	=> 'View passwords list',
	'v_log_a_add_password' 			=> 'Add password',
	'v_log_a_edit_password' 		=> 'Edit password',
	'v_log_a_edit_password_notes' 	=> 'Edit password notes',
	'v_log_a_delete_password' 		=> 'Delete password', 
	'v_log_a_copy_password' 		=> 'Copy password',
	'v_log_a_move_password' 		=> 'Move password',
	'v_log_a_view_user_log' 		=> 'View user log',
	'v_log_a_view_users' 			=> 'View users',
	'v_log_a_view_user' 			=> 'View user',
	'v_log_a_edit_user' 			=> 'Edit user',
	'v_log_a_add_user' 				=> 'Add user',
	'v_log_a_delete_user' 			=> 'Delete user',
	'v_log_a_change_user_password' 	=> 'Change user password',
	'v_log_a_change_user_language' 	=> 'Change user language',
	'v_log_a_view_my_account' 		=> 'View my account',
	'v_log_a_edit_my_account' 		=> 'Edit my account',
	'v_log_a_change_my_password' 	=> 'Change my password',
	'v_log_a_change_my_language' 	=> 'Change my language',
	'v_log_a_view_help' 			=> 'View help',
	'v_log_a_view_export_import_help' => 'View export/import help',
	'v_log_a_view_my_export_import_help' => 'View my passwords export/import help',
	'v_log_a_view_advsearch_help' 	=> 'View advanced search help',
	'v_log_a_view_settings' 		=> 'View settings',
	'v_log_a_add_license' 			=> 'Add license',
	'v_log_a_delete_license' 		=> 'Delete license',
	'v_log_a_change_editing_policy' => 'Change editing policy',
	'v_log_a_export_passwords' 		=> 'Export passwords',
	'v_log_a_export_my_passwords' 	=> 'Export my passwords',
	'v_log_a_import_passwords' 		=> 'Import passwords',
	'v_log_a_import_my_passwords' 	=> 'Import my passwords',
	'v_log_a_delete_import_log' 	=> 'Delete import log',
	'v_log_a_delete_my_import_log' 	=> 'Delete my import log',
	'v_log_a_view_projects_list' 	=> 'View [PRJS] list',
	'v_log_a_add_project' 			=> 'Add [PRJ]',
	'v_log_a_edit_project' 			=> 'Edit [PRJ]',
	'v_log_a_archive_project' 		=> 'Archive [PRJ]',
	'v_log_a_unarchive_project' 	=> 'Un-archive [PRJ]',
	'v_log_a_delete_project' 		=> 'Delete [PRJ]',
	'v_log_a_delete_user_from_group' => 'Delete user from group',
	'v_log_a_add_user_to_group' 	=> 'Add user to group',
	'v_log_a_activate_user' 		=> 'Activate user',
	'v_log_a_deactivate_user' 		=> 'Deactivate user',
	'v_log_a_view_groups' 			=> 'View groups',
	'v_log_a_view_group' 			=> 'View group',
	'v_log_a_delete_group' 			=> 'Delete group',
	'v_log_a_edit_group' 			=> 'Edit group',
	'v_log_a_add_group' 			=> 'Add group',
	'v_log_a_filter_log' 			=> 'Filter log',
	'v_log_a_import_demo_content_begin' => 'Import demo content begin',
	'v_log_a_import_demo_content_end' => 'Import demo content end',
	'v_log_a_send_test_email' 		=> 'Send test email',
	'v_log_a_enable_two_factor_auth' => 'Enable two-factor authentication',
	'v_log_a_disable_two_factor_auth' => 'Disable two-factor authentication',
	'v_log_a_disable_two_factor_auth_act' => 'Disable two-factor authentication for my account',
	'v_log_a_enable_two_factor_auth_act' => 'Enable two-factor authentication for my account',
	'v_log_a_installation_successful' => 'Installation successful',
	'v_log_a_upgrade_successful' 	=> 'Upgrade successful',
	'v_log_a_int_upgrade_successful' => 'Intermediate upgrade successful',
	'v_log_a_decrypted_aue' 		=> 'Decrypt Access, Username, Email (upgrade to 4.50.100)',
	'v_log_a_disable_two_factor_auth_usr' => 'Disable two-factor authentication for a user',
	'v_log_a_blocked_ip_trying_access' => 'Blocked IP trying access',
	'v_log_a_add_ip_to_block' 		=> 'Add IP address to block',
	'v_log_a_delete_blocked_ip' 	=> 'Delete Blocked IP Address',
	'v_log_a_enforce_2fa' 			=> 'Enforce two-factor authentication on all users',
	'v_log_a_stop_enforce_2fa' 		=> 'Stop enforcing two-factor authentication on all users',
	'v_log_a_change_pgen_config' 	=> 'Change password generator configuration',
	'v_log_a_change_email_config' 	=> 'Change email configuration',
	'v_log_a_enable_auto_ip_blocking' => 'Enable automatic IP address blocking',
	'v_log_a_disable_auto_ip_blocking' => 'Disable automatic IP address blocking',
	'v_log_a_edit_ipba_settings' 	=> 'Edit automatic IP address blocking settings',
	'v_log_a_block_ip_automatically' => 'Block IP address automatically',
	'v_log_a_sent_ipba_notification' => 'Sent automatically blocked IP notification',
	'v_log_a_set_prj_favorite' 		=> 'Set the [PRJ] as favorite',
	'v_log_a_unset_prj_favorite' 	=> 'Set the [PRJ] as not favorite',
	'v_log_a_set_pwd_favorite' 		=> 'Set the password as favorite',
	'v_log_a_unset_pwd_favorite' 	=> 'Set the password as not favorite',
	'v_log_a_copy_to_clipboard' 	=> 'Copy password to clipboard',
	'v_log_a_upload_file' 			=> 'Upload file',
	'v_log_a_download_file' 		=> 'Download file',
	'v_log_a_download_file_error' 	=> 'Download file error',
	'v_log_a_download_file_external' => 'Download file (external)',
	'v_log_a_delete_file' 			=> 'Delete file',
	'v_log_a_edit_file_notes' 		=> 'Edit file notes',
	'v_log_a_enable_ldap_authentication' => 'Enable LDAP authentication',
	'v_log_a_disable_ldap_authentication' => 'Disable LDAP authentication',
	'v_log_a_edit_ldap_config' 		=> 'Edit LDAP authentication configuration',
	'v_log_a_test_ldap' 			=> 'Test LDAP server connectivity',
	'v_log_a_add_user_ldap' 		=> 'Add user (LDAP/AD)',
	'v_log_a_ldap_authenticate_ok' 	=> 'LDAP authentication successful',
	'v_log_a_ldap_authenticate_ko' 	=> 'LDAP authentication failed',
	'v_log_a_cnv_normal' 			=> 'Convert the user to a normal (not LDAP) user',
	'v_log_a_cnv_ldap' 				=> 'Convert the user to an LDAP user',
	'v_log_a_ldap_search' 			=> 'LDAP search to import users',
	'v_log_a_import_user_ldap' 		=> 'Add user (LDAP import)',
	'v_log_a_set_timeout' 			=> 'Set timeout',
	'v_log_a_edit_password_security' => 'Edit password security',
	'v_log_a_check_version' 		=>'Check latest version',
	'v_log_a_configure_version_checking' => 'Configure version checking',
	'v_log_a_password_shown' 		=> 'Password shown (Show password or Copy password to clipboard)',
	'v_log_a_view_mypasswords_list' => 'View my passwords list',
	'v_log_a_mycopy_to_clipboard' 	=> 'Copy my password to clipboard',
	'v_log_a_show_mypassword' 		=> 'Show my password',
	'v_log_a_view_mypassword' 		=> 'View my password',
	'v_log_a_delete_mypassword' 	=> 'Delete my password',
	'v_log_a_add_mypassword' 		=> 'Add my password',
	'v_log_a_edit_mypassword' 		=> 'Edit my password',
	'v_log_a_edit_custom_fields' 	=> 'Edit custom fields configuration',
	'v_log_a_view_history_record' 	=> 'View password history record',
	'v_log_a_attach_su_license'	 	=> 'Attach Support and Updates license',
	'v_log_a_enable_api_access' 	=> 'Enable API access',
	'v_log_a_disable_api_access' 	=> 'Disable API access',
	'v_log_a_unauthorized_api_request' => 'Unauthorized API Request',
	'v_log_a_count_projects_list' 	=> 'Count number of [PRJS]',
	'v_log_a_count_passwords_list' 	=> 'Count number of passwords',
	'v_log_a_generate_password' 	=> 'Generate password',
	'v_log_a_count_passwords_project' => 'Count the passwords of a [PRJ]',
	'v_log_a_count_users' 			=> 'Count number of users',
	'v_log_a_count_groups' 			=> 'Count number of groups',
	'v_log_a_renew_api_keys' 		=> 'Renew API Keys',
	'v_log_a_renew_api_keys_api_only_user' => 'Renew API Keys (API only user)',
	'v_log_a_gen_exp_notif' 		=> 'Generate expiration notifications',
	'v_log_a_send_notifications_email' => 'Send notifications by email',
	'v_log_a_edit_expiration_configuration' => 'Edit expiration configuration',
	'v_log_a_add_cf_template' 		=> 'Add custom fields template',
	'v_log_a_edit_cf_template' 		=> 'Edit custom fields template',
	'v_log_a_delete_cf_template' 	=> 'Delete custom fields template',
	'v_log_a_edit_cftemplate_new_pwd' => 'Edit custom fields template for new passwords',
	'v_log_a_edit_password_locking' => 'Edit password locking', 
	'v_log_a_unlock_reason' 		=> 'Unlock password',
	'v_log_a_copy_mypassword' 		=> 'Copy my password to a [PRJ]',
	'v_log_a_move_mypassword' 		=> 'Move my password to a [PRJ]',
	'v_log_a_get_version' 			=> 'Get version',
	'v_log_a_count_mypasswords_list' => 'Count number of my passwords',
	'v_log_a_delete_all_my_passwords' => 'Delete all my passwords',
	'v_log_a_enable_external_sharing' => 'Enable external sharing',
	'v_log_a_disable_external_sharing' => 'Disable external sharing',
	'v_log_a_edit_external_sharing' => 'Edit external sharing',
	'v_log_a_view_password_external' => 'View password (external)',
	'v_log_a_show_password_external' => 'Show password (external)',
	'v_log_a_copy_to_clipboard_external' => 'Copy password to clipboard (external)',
	//'v_log_a_view_file' 			=> 'View file notes',
	'v_log_a_view_file_external' 	=> 'View file (external)',
	'v_log_a_edit_project_security' => 'Edit [PRJ] security',
	'v_log_a_filter_tree' 			=> 'Filter tree',
	'v_log_a_change_parent' 		=> 'Change parent',
	'v_log_a_list_subprojects'		=> 'List [SUBPRJS]',
	'v_log_a_export' 				=> 'Export',
	'v_log_a_set_api_only_user' 	=> 'Set user as API only',
	'v_log_a_unset_api_only_user' 	=> 'Unset user as API only',
	'v_log_a_view_user_api_keys' 	=> 'View user API keys (API only user)',
	'v_log_a_view_eula' 			=> 'View EULA',
	'v_log_a_delete_data' 			=> 'Delete data (for importing demo content)',
	
	// model
	'm_log_not_logged'				=> 'not logged', // ip address (in demo)
	'm_log_duplicated_from'			=> 'Duplicated from', // password
	'm_log_copied_from'				=> 'Copied from',  // password
	'm_log_moved_from'				=> 'Moved from',  // password
	'm_log_no_name'					=> 'no name',

	// v4
	'v_log_a_send_unlock_request'	=> 'Send unlock request',
	'v_log_a_grant_unlock_request'	=> 'Grant unlock request',
	'v_log_a_revoke_unlock_request'	=> 'Revoke unlock request',

	// v6
	'v_log_a_ldap_sync_enable' 		=> 'Enable LDAP Sync',
	'v_log_a_ldap_sync_disable' 	=> 'Disable LDAP Sync',
	'v_log_a_ldap_sync_add_user' 	=> 'Add user (LDAP Sync)',
	'v_log_a_ldap_sync_update_user' => 'Update user (LDAP Sync)',
	'v_log_a_ldap_sync_addu_begin' 	=> 'LDAP Sync add/update users begin',
	'v_log_a_ldap_sync_delu_begin' 	=> 'LDAP Sync delete users begin',
	'v_log_a_ldap_sync_addu_end' 	=> 'LDAP Sync add/update users end',
	'v_log_a_ldap_sync_delu_end' 	=> 'LDAP Sync delete users end',
	'v_log_a_ldap_sync_view_objects' => 'View LDAP Sync objects',
	'v_log_a_ldap_sync_error' 		=> 'LDAP Sync error',
	'v_log_a_ldap_sync_view_object' => 'View LDAP Sync Object',
	'v_log_a_ldap_sync_new_object' 	=> 'New LDAP Sync Object',
	'v_log_a_ldap_sync_edit_object' => 'Edit LDAP Sync Object',
	'v_log_a_ldap_sync_disable_object' => 'Disable LDAP Sync Object',
	'v_log_a_ldap_sync_enable_object' => 'Enable LDAP Sync Object',
	'v_log_a_ldap_sync_del_object' 	=> 'Delete LDAP Sync Object',
	'v_log_a_ldap_sync_test_object' => 'Test LDAP Sync Object',
	'v_log_a_ldap_sync_del_user' 	=> 'Delete user (LDAP Sync)',
	'v_log_a_ldap_sync_addg_begin' 	=> 'LDAP Sync add/update groups begin',
	'v_log_a_ldap_sync_addg_end' 	=> 'LDAP Sync add/update groups end',
	'v_log_a_ldap_sync_add_group' 	=> 'Add group (LDAP Sync)',
	'v_log_a_ldap_sync_update_group'=> 'Update group (LDAP Sync)',
	'v_log_a_ldap_sync_autg' 		=> 'Add user to group (LDAP Sync)',
	'v_log_a_ldap_sync_dufg' 		=> 'Delete user from group (LDAP Sync)',
	'v_log_a_ldap_sync_delg_begin' 	=> 'LDAP Sync delete groups begin',
	'v_log_a_ldap_sync_delg_end' 	=> 'LDAP Sync delete groups end',
	'v_log_a_ldap_sync_del_group' 	=> 'Delete group (LDAP Sync)',

	// v8
	'v_log_a_edit_api_sec' 			=> 'Edit API Security',

	// v9
	'v_log_a_link_password' 		=> 'Link Password',
	'm_log_source_password_linked' 	=> 'Source password id', 
	'v_log_a_unlink_password' 		=> 'Unlink Password',
	'v_log_a_enable_lin_pwd_creation' => 'Enable linked passwords creation',
	'v_log_a_disable_lin_pwd_creation' => 'Disable linked passwords creation',

	'v_log_a_enable_password_reset' => 'Enable password reset',
	'v_log_a_disable_password_reset' => 'Disable password reset',

	// v10
	'v_log_a_archive_password' 		=> 'Archive password',
	'v_log_a_unarchive_password' 	=> 'Un-archive password',

	// v11
	'v_log_origin_ext'				=> 'Extension',
	'v_log_a_extension_connect' 	=> 'Browser Extension connect',
	'v_log_a_extension_disconnect' 	=> 'Browser Extension disconnect',
	'v_log_a_enable_saml_authentication' => 'Enable SAML authentication',
	'v_log_a_disable_saml_authentication' => 'Disable SAML authentication',
	'v_log_a_saml_authenticate_ok' 	=> 'SAML authentication successful',
	'v_log_a_saml_authenticate_ko' 	=> 'SAML authentication failed',
	'v_log_a_saml_logout_ok' 		=> 'SAML logout successful',
	'v_log_a_saml_logout_ko' 		=> 'SAML logout failed',
	'v_log_a_add_user_saml' 		=> 'Add user (SAML)',
	'v_log_a_cnv_normal_saml' 		=> 'Convert the user to a normal (not SAML) user',
	'v_log_a_cnv_saml' 				=> 'Convert the user to a SAML user',
	'v_log_a_edit_saml_settigns' 	=> 'Edit SAML settings',

	'v_log_a_ext_set_preference' 	=> 'Set extension preference',

	// v12
	'v_log_a_count_files'			=> 'Count the number of files',
	'v_log_a_view_file' 			=> 'View file notes/info', // replace the current one above
	'v_log_a_edit_password_reset_url' => 'Edit password reset URL',

	// v13
	'v_log_a_change_upr_config' 	=> 'Change user password rules configuration',

	// v14
	'v_log_a_edit_pwm'				=> 'Change the manager for new passwords',

	// v15
	'v_log_a_delete_password_permanently' => 'Permanently delete password',
	'v_log_a_restore_password' 		=> 'Restore password',

	'v_log_a_view_trash_bin'		=> 'View trash bin',

	'v_log_a_delete_project_permanently' => 'Permanently delete [PRJ]',

	'v_log_a_view_my_trash_bin' 	=> 'View my trash bin',

	'v_log_a_restore_mypassword' 	=> 'Restore my password',
	'v_log_a_delperm_mypassword'	=> 'Permanently delete my password',
	'v_log_a_empty_my_trash' 		=> 'Empty My Trash Bin',

	// v16
	'v_log_a_get_otp_directly'		=> 'Get OTP values directly',

	// v18
	'v_log_a_archive_mypassword' 	=> 'Archive my password',
	'v_log_a_unarchive_mypassword' 	=> 'Un-Archive my password',

	// v19
	'v_log_a_bulk_action_begin'		=> 'Bulk action begin',
	'v_log_a_bulk_action_end'		=> 'Bulk action end',
	'v_log_a_set_password_manager'	=> 'Set password manager',

	// v20
	'v_log_a_edit_my_custom_fields' => 'Edit my custom fields',
	'v_log_a_get_my_otp_directly' 	=> 'Get My OTP directly',

	'v_log_a_set_mypwd_favorite' 	=> 'Set the personal password as favorite',
	'v_log_a_unset_mypwd_favorite' 	=> 'Set the personal password as not favorite',

	// v21
	'v_log_a_calculate_strength_start' 		=> 'Start Calculate Strength Process',
	'v_log_a_calculate_strength_stop' 		=> 'Stop Calculate Strength Process',
	'v_log_a_calculate_strength_finish' 	=> 'Finish Calculate Strength Process',
	
);