<?php
$lang = array (
	'c_log_title'					=> '活動記録',
	'v_log_date_time'				=> '日時',
	'v_log_ip_addr'					=> 'IPアドレス',
	'v_log_user'					=> 'ユーザー',
	'v_log_action'					=> 'アクション',
	'v_log_related_prj_pwd'			=> '関連[PRJ] / パスワード',
	'v_log_related_pwd' 			=> '関連パスワード',
	'v_log_additional_data'			=> '追加データ',
	'v_log_origin'					=> '起源',
	'v_log_no_entries'				=> '現在のフィルターにはログエントリーはありません。',
	'v_log_filter'					=> 'フィルター',
	'v_log_clear_filter' 			=> '値の消去とフィルタの非表示',

	'v_log_filter_date'				=> '日付',
	'v_log_filter_date_always' 		=> '常に',
	'v_log_filter_date_today' 		=> '今日',
	'v_log_filter_date_yesterday' 	=> '昨日',
	'v_log_filter_date_this_month' 	=> '今月',
	'v_log_filter_date_prev_month' 	=> '前月',
	'v_log_filter_date_this_year' 	=> '今年',
	'v_log_filter_date_prev_year' 	=> '前年',

	'v_log_origin_web'				=> 'ウェブ',
	'v_log_origin_api'				=> 'API',

	'v_log_users_all'				=> 'すべて',
	'v_log_actions_all'				=> 'すべて',
	'v_log_origins_all'				=> 'すべて',

	// Actions
	'v_log_a_view_password' 		=> 'パスワードデータの表示',
	'v_log_a_view_project' 			=> '[PRJ]を見る',
	'v_log_a_login_successful' 		=> 'ログイン成功',
	'v_log_a_login_failed' 			=> 'ログインに失敗しました',
	'v_log_a_logout' 				=> 'ログアウト',
	'v_log_a_password_reset' 		=> 'パスワードリセット（ユーザー）',
	'v_log_a_show_password' 		=> 'パスワードを表示する',
	'v_log_a_view_project_log' 		=> '[PRJ]ログを見る',
	'v_log_a_view_log' 				=> 'ログを見る',
	'v_log_a_view_passwords_list' 	=> 'パスワード一覧を見る',
	'v_log_a_add_password' 			=> 'パスワードの追加',
	'v_log_a_edit_password' 		=> 'パスワードの編集',
	'v_log_a_edit_password_notes' 	=> 'パスワードのメモを編集する',
	'v_log_a_delete_password' 		=> 'パスワードの削除', 
	'v_log_a_copy_password' 		=> 'パスワードをコピーする',
	'v_log_a_move_password' 		=> 'パスワードの移動',
	'v_log_a_view_user_log' 		=> 'ユーザーログの表示',
	'v_log_a_view_users' 			=> 'ユーザーを見る',
	'v_log_a_view_user' 			=> 'ユーザーを見る',
	'v_log_a_edit_user' 			=> '編集ユーザー',
	'v_log_a_add_user' 				=> 'ユーザー追加',
	'v_log_a_delete_user' 			=> 'ユーザー削除',
	'v_log_a_change_user_password' 	=> 'ユーザーパスワードの変更',
	'v_log_a_change_user_language' 	=> 'ユーザー言語の変更',
	'v_log_a_view_my_account' 		=> 'アカウントを見る',
	'v_log_a_edit_my_account' 		=> 'アカウントの編集',
	'v_log_a_change_my_password' 	=> 'パスワードの変更',
	'v_log_a_change_my_language' 	=> '言語を変更する',
	'v_log_a_view_help' 			=> 'ヘルプを見る',
	'v_log_a_view_export_import_help' => 'エクスポート/インポートのヘルプを見る',
	'v_log_a_view_my_export_import_help' => 'パスワードのエクスポート/インポート',
	'v_log_a_view_advsearch_help' 	=> '高度な検索ヘルプを見る',
	'v_log_a_view_settings' 		=> '設定を見る',
	'v_log_a_add_license' 			=> 'ライセンスの追加',
	'v_log_a_delete_license' 		=> 'ライセンス削除',
	'v_log_a_change_editing_policy' => '編集ポリシーの変更',
	'v_log_a_export_passwords' 		=> 'パスワードのエクスポート',
	'v_log_a_export_my_passwords' 	=> 'パスワードをエクスポートする',
	'v_log_a_import_passwords' 		=> 'パスワードのインポート',
	'v_log_a_import_my_passwords' 	=> 'パスワードのインポート',
	'v_log_a_delete_import_log' 	=> 'インポートログの削除',
	'v_log_a_delete_my_import_log' 	=> 'インポートログの削除',
	'v_log_a_view_projects_list' 	=> '[PRJS]一覧を見る',
	'v_log_a_add_project' 			=> '[PRJ]を追加',
	'v_log_a_edit_project' 			=> '[PRJ]を編集する',
	'v_log_a_archive_project' 		=> 'アーカイブ[PRJ］',
	'v_log_a_unarchive_project' 	=> 'アーカイブ解除[PRJ］',
	'v_log_a_delete_project' 		=> '[PRJ]を削除する',
	'v_log_a_delete_user_from_group' => 'グループからユーザーを削除する',
	'v_log_a_add_user_to_group' 	=> 'ユーザーをグループに追加する',
	'v_log_a_activate_user' 		=> 'ユーザーをアクティブにする',
	'v_log_a_deactivate_user' 		=> 'ユーザーの無効化',
	'v_log_a_view_groups' 			=> 'グループを見る',
	'v_log_a_view_group' 			=> 'グループを見る',
	'v_log_a_delete_group' 			=> 'グループ削除',
	'v_log_a_edit_group' 			=> '編集グループ',
	'v_log_a_add_group' 			=> 'グループ追加',
	'v_log_a_filter_log' 			=> 'フィルターログ',
	'v_log_a_import_demo_content_begin' => 'デモ・コンテンツのインポート開始',
	'v_log_a_import_demo_content_end' => 'デモ・コンテンツのインポート終了',
	'v_log_a_send_test_email' 		=> 'テストメールを送信する',
	'v_log_a_enable_two_factor_auth' => '二要素認証を有効にする',
	'v_log_a_disable_two_factor_auth' => '二要素認証を無効にする',
	'v_log_a_disable_two_factor_auth_act' => 'アカウントの二要素認証を無効にする',
	'v_log_a_enable_two_factor_auth_act' => '自分のアカウントで二要素認証を有効にする',
	'v_log_a_installation_successful' => 'インストール成功',
	'v_log_a_upgrade_successful' 	=> 'アップグレード成功',
	'v_log_a_int_upgrade_successful' => '中間アップグレード成功',
	'v_log_a_decrypted_aue' 		=> 'アクセス、ユーザー名、電子メールの復号化 (4.50.100 にアップグレード)',
	'v_log_a_disable_two_factor_auth_usr' => 'ユーザーの二要素認証を無効にする',
	'v_log_a_blocked_ip_trying_access' => 'アクセスを試みるIPをブロック',
	'v_log_a_add_ip_to_block' 		=> 'ブロックするIPアドレスを追加する',
	'v_log_a_delete_blocked_ip' 	=> 'ブロックされたIPアドレスの削除',
	'v_log_a_enforce_2fa' 			=> '全ユーザーに二要素認証を強制する',
	'v_log_a_stop_enforce_2fa' 		=> '全ユーザーへの2ファクタ認証の強制をやめる',
	'v_log_a_change_pgen_config' 	=> 'パスワード・ジェネレーターの設定を変更する',
	'v_log_a_change_email_config' 	=> 'Eメール設定の変更',
	'v_log_a_enable_auto_ip_blocking' => '自動IPアドレスブロックを有効にする',
	'v_log_a_disable_auto_ip_blocking' => '自動IPアドレスブロックを無効にする',
	'v_log_a_edit_ipba_settings' 	=> '自動IPアドレスブロック設定の編集',
	'v_log_a_block_ip_automatically' => 'IPアドレスを自動的にブロック',
	'v_log_a_sent_ipba_notification' => '自動的にブロックされたIP通知を送信',
	'v_log_a_set_prj_favorite' 		=> '[PRJ]をお気に入りに設定する',
	'v_log_a_unset_prj_favorite' 	=> '[PRJ]をお気に入りに設定しない',
	'v_log_a_set_pwd_favorite' 		=> 'パスワードをお気に入りに設定する',
	'v_log_a_unset_pwd_favorite' 	=> 'パスワードをお気に入りに設定しない',
	'v_log_a_copy_to_clipboard' 	=> 'パスワードをクリップボードにコピーする',
	'v_log_a_upload_file' 			=> 'ファイルのアップロード',
	'v_log_a_download_file' 		=> 'ダウンロードファイル',
	'v_log_a_download_file_error' 	=> 'ダウンロードファイルエラー',
	'v_log_a_download_file_external' => 'ダウンロードファイル（外部）',
	'v_log_a_delete_file' 			=> 'ファイルの削除',
	'v_log_a_edit_file_notes' 		=> 'ファイルノートの編集',
	'v_log_a_enable_ldap_authentication' => 'LDAP認証を有効にする',
	'v_log_a_disable_ldap_authentication' => 'LDAP認証を無効にする',
	'v_log_a_edit_ldap_config' 		=> 'LDAP認証設定の編集',
	'v_log_a_test_ldap' 			=> 'LDAPサーバー接続のテスト',
	'v_log_a_add_user_ldap' 		=> 'ユーザーの追加（LDAP/AD）',
	'v_log_a_ldap_authenticate_ok' 	=> 'LDAP認証に成功',
	'v_log_a_ldap_authenticate_ko' 	=> 'LDAP認証に失敗',
	'v_log_a_cnv_normal' 			=> 'ユーザーを通常の（LDAPではない）ユーザーに変換する。',
	'v_log_a_cnv_ldap' 				=> 'ユーザーをLDAPユーザーに変換する',
	'v_log_a_ldap_search' 			=> 'ユーザーをインポートするためのLDAP検索',
	'v_log_a_import_user_ldap' 		=> 'ユーザー追加（LDAPインポート）',
	'v_log_a_set_timeout' 			=> 'タイムアウトの設定',
	'v_log_a_edit_password_security' => 'パスワード・セキュリティの編集',
	'v_log_a_check_version' 		=>'Check latest version',
	'v_log_a_configure_version_checking' => 'バージョンチェックの設定',
	'v_log_a_password_shown' 		=> 'パスワードの表示（パスワードを表示またはパスワードをクリップボードにコピー）',
	'v_log_a_view_mypasswords_list' => 'パスワードリストを見る',
	'v_log_a_mycopy_to_clipboard' 	=> 'パスワードをクリップボードにコピーする',
	'v_log_a_show_mypassword' 		=> 'パスワードを表示する',
	'v_log_a_view_mypassword' 		=> 'パスワードを見る',
	'v_log_a_delete_mypassword' 	=> 'パスワードの削除',
	'v_log_a_add_mypassword' 		=> 'パスワードを追加する',
	'v_log_a_edit_mypassword' 		=> 'パスワードの編集',
	'v_log_a_edit_custom_fields' 	=> 'カスタムフィールドの設定を編集する',
	'v_log_a_view_history_record' 	=> 'パスワード履歴を見る',
	'v_log_a_attach_su_license'	 	=> 'サポートとアップデートのライセンスを添付',
	'v_log_a_enable_api_access' 	=> 'APIアクセスを有効にする',
	'v_log_a_disable_api_access' 	=> 'APIアクセスを無効にする',
	'v_log_a_unauthorized_api_request' => '不正なAPIリクエスト',
	'v_log_a_count_projects_list' 	=> '[PRJS]のカウント数',
	'v_log_a_count_passwords_list' 	=> 'パスワードの数を数える',
	'v_log_a_generate_password' 	=> 'パスワードの生成',
	'v_log_a_count_passwords_project' => '[PRJ]のパスワードを数える',
	'v_log_a_count_users' 			=> 'ユーザー数のカウント',
	'v_log_a_count_groups' 			=> 'グループ数を数える',
	'v_log_a_renew_api_keys' 		=> 'APIキーを更新する',
	'v_log_a_renew_api_keys_api_only_user' => 'APIキーを更新する（APIのみのユーザー）',
	'v_log_a_gen_exp_notif' 		=> '期限切れ通知の生成',
	'v_log_a_send_notifications_email' => 'Eメールで通知を送信',
	'v_log_a_edit_expiration_configuration' => '有効期限設定の編集',
	'v_log_a_add_cf_template' 		=> 'カスタムフィールドテンプレートの追加',
	'v_log_a_edit_cf_template' 		=> 'カスタムフィールドテンプレートの編集',
	'v_log_a_delete_cf_template' 	=> 'カスタムフィールドテンプレートの削除',
	'v_log_a_edit_cftemplate_new_pwd' => '新しいパスワード用のカスタムフィールドテンプレートを編集する',
	'v_log_a_edit_password_locking' => '編集パスワードロック', 
	'v_log_a_unlock_reason' 		=> 'パスワードロック解除',
	'v_log_a_copy_mypassword' 		=> 'パスワードを[PRJ]にコピーする',
	'v_log_a_move_mypassword' 		=> 'パスワードを[PRJ]に移す',
	'v_log_a_get_version' 			=> 'バージョンを取得する',
	'v_log_a_count_mypasswords_list' => 'パスワードの数を数える',
	'v_log_a_delete_all_my_passwords' => 'すべてのパスワードを削除する',
	'v_log_a_enable_external_sharing' => '外部共有を有効にする',
	'v_log_a_disable_external_sharing' => '外部共有を無効にする',
	'v_log_a_edit_external_sharing' => '外部共有の編集',
	'v_log_a_view_password_external' => 'パスワードを見る（外部）',
	'v_log_a_show_password_external' => 'パスワードを表示する（外部）',
	'v_log_a_copy_to_clipboard_external' => 'パスワードをクリップボードにコピーする（外部）',
	//'v_log_a_view_file' 			=> 'ファイルノートを見る',
	'v_log_a_view_file_external' 	=> 'ファイルを見る（外部）',
	'v_log_a_edit_project_security' => '[PRJ]セキュリティの編集',
	'v_log_a_filter_tree' 			=> 'フィルターツリー',
	'v_log_a_change_parent' 		=> '親を変更する',
	'v_log_a_list_subprojects'		=> 'リスト [SUBPRJS］',
	'v_log_a_export' 				=> '輸出',
	'v_log_a_set_api_only_user' 	=> 'ユーザーをAPIのみに設定する',
	'v_log_a_unset_api_only_user' 	=> 'ユーザーをAPIのみに設定解除',
	'v_log_a_view_user_api_keys' 	=> 'ユーザーAPIキーの表示（APIのみのユーザー）',
	'v_log_a_view_eula' 			=> 'EULAを見る',
	'v_log_a_delete_data' 			=> 'データの削除（デモコンテンツのインポート用）',
	
	// model
	'm_log_not_logged'				=> '未記録', // ip address (in demo)
	'm_log_duplicated_from'			=> 'からの複製', // password
	'm_log_copied_from'				=> 'よりコピー',  // password
	'm_log_moved_from'				=> 'から移動',  // password
	'm_log_no_name'					=> '名無し',

	// v4
	'v_log_a_send_unlock_request'	=> 'ロック解除リクエストを送信',
	'v_log_a_grant_unlock_request'	=> 'ロック解除要求の許可',
	'v_log_a_revoke_unlock_request'	=> 'ロック解除要求を取り消す',

	// v6
	'v_log_a_ldap_sync_enable' 		=> 'LDAP同期を有効にする',
	'v_log_a_ldap_sync_disable' 	=> 'LDAP同期を無効にする',
	'v_log_a_ldap_sync_add_user' 	=> 'ユーザー追加（LDAP同期）',
	'v_log_a_ldap_sync_update_user' => 'ユーザー更新（LDAP同期）',
	'v_log_a_ldap_sync_addu_begin' 	=> 'LDAP同期によるユーザーの追加/更新開始',
	'v_log_a_ldap_sync_delu_begin' 	=> 'LDAP同期によるユーザー削除開始',
	'v_log_a_ldap_sync_addu_end' 	=> 'LDAP同期によるユーザーの追加/更新 終了',
	'v_log_a_ldap_sync_delu_end' 	=> 'LDAP同期削除ユーザー終了',
	'v_log_a_ldap_sync_view_objects' => 'LDAP同期オブジェクトの表示',
	'v_log_a_ldap_sync_error' 		=> 'LDAP同期エラー',
	'v_log_a_ldap_sync_view_object' => 'LDAP同期オブジェクトの表示',
	'v_log_a_ldap_sync_new_object' 	=> '新しいLDAP同期オブジェクト',
	'v_log_a_ldap_sync_edit_object' => 'LDAP同期オブジェクトの編集',
	'v_log_a_ldap_sync_disable_object' => 'LDAP同期オブジェクトを無効にする',
	'v_log_a_ldap_sync_enable_object' => 'LDAP同期オブジェクトを有効にする',
	'v_log_a_ldap_sync_del_object' 	=> 'LDAP同期オブジェクトの削除',
	'v_log_a_ldap_sync_test_object' => 'テストLDAP同期オブジェクト',
	'v_log_a_ldap_sync_del_user' 	=> 'ユーザー削除（LDAP同期）',
	'v_log_a_ldap_sync_addg_begin' 	=> 'LDAP同期グループ追加/更新開始',
	'v_log_a_ldap_sync_addg_end' 	=> 'LDAP同期グループの追加/更新 終了',
	'v_log_a_ldap_sync_add_group' 	=> 'グループの追加（LDAP同期）',
	'v_log_a_ldap_sync_update_group'=> 'グループの更新（LDAP同期）',
	'v_log_a_ldap_sync_autg' 		=> 'ユーザーをグループに追加（LDAP同期）',
	'v_log_a_ldap_sync_dufg' 		=> 'グループからユーザーを削除（LDAP同期）',
	'v_log_a_ldap_sync_delg_begin' 	=> 'LDAP同期削除グループ開始',
	'v_log_a_ldap_sync_delg_end' 	=> 'LDAP同期削除グループ終了',
	'v_log_a_ldap_sync_del_group' 	=> 'グループ削除（LDAP同期）',

	// v8
	'v_log_a_edit_api_sec' 			=> 'APIセキュリティの編集',

	// v9
	'v_log_a_link_password' 		=> 'リンクパスワード',
	'm_log_source_password_linked' 	=> 'ソースパスワードID', 
	'v_log_a_unlink_password' 		=> 'パスワードの解除',
	'v_log_a_enable_lin_pwd_creation' => 'リンクされたパスワードの作成を有効にする',
	'v_log_a_disable_lin_pwd_creation' => 'リンクされたパスワードの作成を無効にする',

	'v_log_a_enable_password_reset' => 'パスワードリセットを有効にする',
	'v_log_a_disable_password_reset' => 'パスワードリセットを無効にする',

	// v10
	'v_log_a_archive_password' 		=> 'アーカイブパスワード',
	'v_log_a_unarchive_password' 	=> 'アーカイブパスワードの解除',

	// v11
	'v_log_origin_ext'				=> 'エクステンション',
	'v_log_a_extension_connect' 	=> 'ブラウザ拡張機能接続',
	'v_log_a_extension_disconnect' 	=> 'ブラウザ拡張機能の切断',
	'v_log_a_enable_saml_authentication' => 'SAML 認証を有効にする',
	'v_log_a_disable_saml_authentication' => 'SAML 認証を無効にする',
	'v_log_a_saml_authenticate_ok' 	=> 'SAML 認証成功',
	'v_log_a_saml_authenticate_ko' 	=> 'SAML 認証に失敗しました。',
	'v_log_a_saml_logout_ok' 		=> 'SAML ログアウト成功',
	'v_log_a_saml_logout_ko' 		=> 'SAML ログアウトの失敗',
	'v_log_a_add_user_saml' 		=> 'ユーザの追加（SAML）',
	'v_log_a_cnv_normal_saml' 		=> 'ユーザを通常の（SAML ではない）ユーザに変換する。',
	'v_log_a_cnv_saml' 				=> 'ユーザを SAML ユーザに変換する。',
	'v_log_a_edit_saml_settigns' 	=> 'SAML 設定の編集',

	'v_log_a_ext_set_preference' 	=> '拡張機能の優先順位を設定する',

	// v12
	'v_log_a_count_files'			=> 'ファイル数を数える',
	'v_log_a_view_file' 			=> 'ファイルノート/情報を見る', // replace the current one above
	'v_log_a_edit_password_reset_url' => 'パスワードリセットURLの編集',

	// v13
	'v_log_a_change_upr_config' 	=> 'ユーザーパスワードルールの設定変更',

	// v14
	'v_log_a_edit_pwm'				=> '新しいパスワードの管理者を変更する',

	// v15
	'v_log_a_delete_password_permanently' => 'パスワードの永久削除',
	'v_log_a_restore_password' 		=> 'パスワードの復元',

	'v_log_a_view_trash_bin'		=> 'ゴミ箱を見る',

	'v_log_a_delete_project_permanently' => '[PRJ]を永久削除',

	'v_log_a_view_my_trash_bin' 	=> 'ゴミ箱を見る',

	'v_log_a_restore_mypassword' 	=> 'パスワードの復元',
	'v_log_a_delperm_mypassword'	=> 'パスワードを永久に削除する',
	'v_log_a_empty_my_trash' 		=> 'ゴミ箱を空にする',

	// v16
	'v_log_a_get_otp_directly'		=> 'OTP 値を直接取得する',

	// v18
	'v_log_a_archive_mypassword' 	=> 'パスワードをアーカイブする',
	'v_log_a_unarchive_mypassword' 	=> 'パスワードのアーカイブを解除する',

	// v19
	'v_log_a_bulk_action_begin'		=> 'バルクアクション開始',
	'v_log_a_bulk_action_end'		=> 'バルクアクション終了',
	'v_log_a_set_password_manager'	=> 'パスワード・マネージャーを設定する',

	// v20
	'v_log_a_edit_my_custom_fields' => 'カスタムフィールドの編集',
	'v_log_a_get_my_otp_directly' 	=> 'ワンタイムパスワードを直接取得する',

	'v_log_a_set_mypwd_favorite' 	=> '個人パスワードをお気に入りに設定する',
	'v_log_a_unset_mypwd_favorite' 	=> '個人パスワードはお気に入りに設定しない',

	// v21
	'v_log_a_calculate_strength_start' 		=> '強さの計算を開始',
	'v_log_a_calculate_strength_stop' 		=> '強さの計算プロセスを停止する',
	'v_log_a_calculate_strength_finish' 	=> '強度計算を終了する',
	
);